version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashsale
    ports: ["5432:5432"]

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"] # 15672 for the UI

  api:
    build: ./api
    ports: ["3000:3000"]
    depends_on: [postgres, redis, rabbitmq]

  worker:
    build: ./worker
    depends_on: [postgres, redis, rabbitmq]
    deploy:
      replicas: 3 # Simulate 3 parallel workers!

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana
    ports: ["3001:3000"]
    depends_on: [prometheus]